EZ.window=function(b){var c=this;b=b||{};b.window_style=b.window_style||{};b.mask_style=b.mask_style||{};b.content_style=b.content_style||{};b.close_button_style=b.close_button_style||{};b.onopen=b.onopen||EZ.emptyFN;b.onclose=b.onclose||EZ.emptyFN;this.open=function(a){b.onopen(a);c.mask.show(a);c.window.show(a)};this.close=function(a){b.onclose(a);c.mask.hide();c.window.hide()};this.init=function(){for(var a in b.window_style)b.window_style.hasOwnProperty(a)&&(this.window.elem.style[a]=b.window_style[a]);
for(a in b.mask_style)b.mask_style.hasOwnProperty(a)&&(this.mask.elem.style[a]=b.mask_style[a]);for(a in b.content_style)b.content_style.hasOwnProperty(a)&&(this.window_content.elem.style[a]=b.content_style[a]);for(a in b.close_button_style)b.close_button_style.hasOwnProperty(a)&&(this.close_button.elem.style[a]=b.close_button_style[a])};this.mouseCoords=function(a){a=a||window.event;return a.pageX||a.pageY?{x:a.pageX,y:a.pageY}:{x:a.clientX+document.body.scrollLeft-document.body.clientLeft,y:a.clientY+
document.body.scrollTop-document.body.clientTop}};this.window={elem:document.createElement("div"),show:function(a){if("string"==typeof a||"number"==typeof a)b.content=a,c.window_content.elem.innerHTML=b.content;document.body.appendChild(c.window.elem);c.window.elem.style.visibility="visible";setTimeout(function(){c.window.elem.style.top="50%";c.window.elem.style.opacity="1"},0)},hide:function(a){c.window.elem.style.top="40%";c.window.elem.style.opacity="0";setTimeout(function(){c.window.elem.parentNode==
document.body&&(document.body.removeChild(c.window.elem),c.window.elem.style.visibility="hidden")},500)}};this.window.elem.style["background-color"]="#fff";this.window.elem.style.border="3px solid #fff";this.window.elem.style.display="inline-block";this.window.elem.style.left="50%";this.window.elem.style.padding="15px";this.window.elem.style.position="fixed";this.window.elem.style["text-align"]="justify";this.window.elem.style["z-index"]="10";this.window.elem.style.transform="translate(-50%, -50%)";
this.window.elem.style["border-radius"]="10px";this.window.elem.style["box-shadow"]="0 1px 1px 2px rgba(0, 0, 0, 0.4) inset";this.window.elem.style.transition="opacity .5s, top .5s";this.window.elem.style["min-width"]="200px";this.window.elem.style["min-height"]="200px";this.window.elem.style["box-shadow"]="rgba(0, 0, 0, 0.8) 0px 4px 16px";this.window.elem.style.zIndex="1000";this.window.elem.style.visibility="hidden";this.window.elem.style.opacity="0";this.window.elem.style.top="40%";this.window_content=
{elem:document.createElement("div")};this.window_content.elem.innerHTML=b.content||"";this.mask={elem:document.createElement("div"),show:function(){document.body.appendChild(c.mask.elem);setTimeout(function(){c.mask.elem.style.opacity="1"},0)},hide:function(){c.mask.elem.style.opacity="0";setTimeout(function(){c.mask.elem.parentNode==document.body&&document.body.removeChild(c.mask.elem)},1E3)}};this.mask.elem.style.position="fixed";this.mask.elem.style.left="0";this.mask.elem.style.right="0";this.mask.elem.style.top=
"0";this.mask.elem.style.bottom="0";this.mask.elem.style.textAlign="center";this.mask.elem.style.backgroundColor="rgba(0, 0, 0, 0.6)";this.mask.elem.style.zIndex="999";this.mask.elem.setAttribute("close_window","1");this.mask.elem.style.opacity="0";this.mask.elem.style.transition="opacity 1s";this.mask.elem.onclick=this.close;this.close_button={elem:document.createElement("a")};this.close_button.elem.style.display="inline-block";this.close_button.elem.style.color="rgba(255, 255, 255, 0.9)";this.close_button.elem.style.backgroundColor=
"rgba(0, 0, 0, 0.8)";this.close_button.elem.style.cursor="pointer";this.close_button.elem.style["font-size"]="24px";this.close_button.elem.style["text-shadow"]="0 -1px rgba(0, 0, 0, 0.9)";this.close_button.elem.style.height="30px";this.close_button.elem.style["line-height"]="30px";this.close_button.elem.style.position="absolute";this.close_button.elem.style.right="-15px";this.close_button.elem.style["text-align"]="center";this.close_button.elem.style["text-decoration"]="none";this.close_button.elem.style.top=
"-15px";this.close_button.elem.style.width="30px";this.close_button.elem.style["border-radius"]="15px";this.close_button.elem.innerHTML="X";this.close_button.elem.setAttribute("close_window","1");this.close_button.elem.onclick=this.close;this.close_button.elem.onmouseover=function(){this.style["background-color"]="rgba(64, 128, 128, 0.8)"};this.close_button.elem.onmouseout=function(){this.style["background-color"]="rgba(0, 0, 0, 0.8)"};this.window.elem.appendChild(this.close_button.elem);this.window.elem.appendChild(this.window_content.elem);
this.init()};